# General.
timezone: America/New_York 
permalink: /blog/:year/:month/:day/:title
include:
  - '.htaccess'
exclude:
  - 'CNAME'
  - 'Gemfile.*'
  - 'LICENSE'
  - 'README.md'
  - 'Vagrantfile'
repository: asadsalman/asadsalman.github.io 
excerpt_separator: <!--more-->
gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

# Variables.
name: Asad Salman 
url: http://asad.co
author: asadsalman 
logo: /assets/images/me.jpg

# SASS.
sass:
  style: :compressed
  sass_dir: _sass

# Markdown.
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
