# General.
timezone: Europe/Madrid
permalink: /blog/:title
include:
  - '.htaccess'
exclude:
  - 'CNAME'
  - 'Gemfile.*'
  - 'LICENSE'
  - 'README.md'
  - 'Vagrantfile'
repository: carlosabalde/www.carlosabalde.com
excerpt_separator: <!--more-->
gems:
  - jekyll-feed

# Variables.
name: Carlos Abalde
description: A selection of random thoughts and useless stuff I write from time to time
google_verification: null
google_analytics: UA-11266890-1

# SASS.
sass:
  style: :compressed
  sass_dir: _sass

# Markdown.
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
